import type { Domain } from "@/types";

export const DEFAULT_DOMAINS: Omit<Domain, "id" | "health_score" | "created_at" | "updated_at">[] =
  [
    {
      slug: "health",
      name: "Health",
      icon: "Heart",
      color: "hsl(142 71% 45%)",
      vision: "",
      purpose: "",
      current_status: "",
      is_active: true,
      sort_order: 0,
    },
    {
      slug: "career",
      name: "Career",
      icon: "Briefcase",
      color: "hsl(217 91% 60%)",
      vision: "",
      purpose: "",
      current_status: "",
      is_active: true,
      sort_order: 1,
    },
    {
      slug: "financial",
      name: "Financial",
      icon: "TrendingUp",
      color: "hsl(38 92% 50%)",
      vision: "",
      purpose: "",
      current_status: "",
      is_active: true,
      sort_order: 2,
    },
    {
      slug: "intellectual",
      name: "Intellectual",
      icon: "BookOpen",
      color: "hsl(258 90% 66%)",
      vision: "",
      purpose: "",
      current_status: "",
      is_active: true,
      sort_order: 3,
    },
    {
      slug: "emotional",
      name: "Emotional",
      icon: "Smile",
      color: "hsl(330 81% 60%)",
      vision: "",
      purpose: "",
      current_status: "",
      is_active: true,
      sort_order: 4,
    },
    {
      slug: "spiritual",
      name: "Spiritual",
      icon: "Compass",
      color: "hsl(190 95% 39%)",
      vision: "",
      purpose: "",
      current_status: "",
      is_active: true,
      sort_order: 5,
    },
    {
      slug: "relationships",
      name: "Relationships",
      icon: "Users",
      color: "hsl(24 95% 53%)",
      vision: "",
      purpose: "",
      current_status: "",
      is_active: true,
      sort_order: 6,
    },
    {
      slug: "family",
      name: "Family",
      icon: "Home",
      color: "hsl(84 81% 44%)",
      vision: "",
      purpose: "",
      current_status: "",
      is_active: true,
      sort_order: 7,
    },
    {
      slug: "social",
      name: "Social",
      icon: "Globe",
      color: "hsl(270 95% 75%)",
      vision: "",
      purpose: "",
      current_status: "",
      is_active: true,
      sort_order: 8,
    },
    {
      slug: "character",
      name: "Character",
      icon: "Shield",
      color: "hsl(350 89% 60%)",
      vision: "",
      purpose: "",
      current_status: "",
      is_active: true,
      sort_order: 9,
    },
    {
      slug: "lifestyle",
      name: "Lifestyle",
      icon: "Leaf",
      color: "hsl(175 77% 40%)",
      vision: "",
      purpose: "",
      current_status: "",
      is_active: true,
      sort_order: 10,
    },
    {
      slug: "legacy",
      name: "Legacy",
      icon: "Star",
      color: "hsl(239 84% 67%)",
      vision: "",
      purpose: "",
      current_status: "",
      is_active: true,
      sort_order: 11,
    },
  ];

export const BLOCK_TYPE_LABELS: Record<string, string> = {
  deep_work: "Deep Work",
  shallow: "Shallow Work",
  meeting: "Meeting",
  ritual: "Ritual",
  rest: "Rest",
  buffer: "Buffer",
};

export const ENERGY_TYPE_LABELS: Record<string, string> = {
  high: "High Energy",
  medium: "Medium Energy",
  low: "Low Energy",
};

export const PRIORITY_LABELS: Record<string, string> = {
  critical: "Critical",
  high: "High",
  medium: "Medium",
  low: "Low",
};

export const REFLECTION_DAILY_TEMPLATE = [
  { key: "wins", label: "What did I complete or accomplish today?" },
  { key: "skipped", label: "What did I skip or defer? Why?" },
  { key: "energy", label: "How was my energy and focus?" },
  { key: "meaningful", label: "What one thing made today meaningful?" },
  { key: "tomorrow", label: "What are my top 3 priorities for tomorrow?" },
];

export const REFLECTION_WEEKLY_TEMPLATE = [
  { key: "wins", label: "What went well this week?" },
  { key: "challenges", label: "What was difficult or blocked?" },
  { key: "learnings", label: "What did I learn?" },
  { key: "energy_pattern", label: "What drained me? What energized me?" },
  { key: "intentions", label: "What are my 3 outcomes for next week?" },
];
